[package]
name = "executor-bots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-spl = "0.29.0"
solana-program = "1.18.22"
axum = { version="0.7.5", features = ["ws"] }
axum-macros = "0.4.1"
commander = "0.1.5"
config = "0.14.0"
dotenv = "0.15.0"
futures-util = "0.3.30"
lru-cache = "0.1.2"
num-bigint = "0.4.6"
vortex-sdk = { git = "https://github.com/kratos2377/vortex-sdk.git" }
serum = "0.4.7"
solana-client = "1.16"
solana-sdk = "1.16"
spl-token = "6.0.0"
tokio = { version = "1.34.0", features = ["full"] }
winston = "0.1.1"
vortex-contracts = { git = "https://github.com/kratos2377/vortex-exchange.git" }
pyth-sdk-solana = "0.10.0"
#serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
strum_macros = "0.25.3"
opentelemetry = "0.22.0"
tracing-opentelemetry = "0.23.0"
num-traits = "0.2.19"
reqwest-eventsource = "0.6.0"
lru = "0.12.4"
