[package]
name = "executor-bots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = { version="0.29.0", features=["derive"] }
anchor-spl = "0.29.0"
solana-program = "1.16"
axum = { version="0.7.5"}
axum-macros = "0.4.1"
config = "0.14.0"
dotenv = "0.15.0"
futures-util = "0.3.30"
num-bigint = "0.4.6"
solana-client = "1.16"
solana-sdk = "1.16"
spl-token = "6.0.0"
tokio = { version = "1.34.0", features = ["full", "sync"] }
#serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
strum_macros = "0.25.3"
opentelemetry = "0.22.0"
tracing-opentelemetry = "0.23.0"
num-traits = "0.2.19"
nano-id = "0.4.0"
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
futures = "0.3.31"
tracing = "0.1.40"
crossbeam = "0.8.4"
bytemuck = "1.17"
thiserror = "2.0.11"
base64 = "0.22.1"
bs58 = "0.5.1"
log = "0.4"
uuid = { version = "1.7.0", features = ["serde", "v4"] }


[build-dependencies]
vortex-idl-gen = { version = "0.1.0", path = "vortex-idl-gen"}
